name: 2d to 3d:
description: "app so far working"

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Specify the Flutter SDK version
environment:
  sdk: ^3.5.4

# Dependencies for the application
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  camera: ^0.11.0+2
  path_provider: ^2.0.11
  process_run: ^1.2.2+1
  http: ^1.2.2
  path: ^1.8.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# Flutter-specific settings
flutter:
  uses-material-design: true  # Use Material Icons

  # Assets
  assets:
    - assets/camera_icon.webp

